apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hypershift-azjx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hypershift-azjx
    app.kubernetes.io/part-of: hypershift-operator
  name: hypershift-azjx
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: hypershift-azjx
status:
  loadBalancer: {}
